USE [AcademyTest]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FilterHistory](
	[Order] [nvarchar](20) NOT NULL,
	[Category] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_FilterHistory] PRIMARY KEY CLUSTERED 
(
	[Order] ASC,
	[Category] ASC

)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO